/*-------------------------------------------------------------------------
 *
 * mys_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef MYS_KWLIST_D_H
#define MYS_KWLIST_D_H

#include "common/kwlookup.h"

static const char MysScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"any_value\0"
	"array\0"
	"as\0"
	"asc\0"
	"ascii\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"auto_increment\0"
	"avg_row_length\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"bit_as_bytea\0"
	"blob\0"
	"bool\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"checksum\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_format\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"contains\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"convert\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"databases\0"
	"date\0"
	"datetime\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delay_key_write\0"
	"delayed\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"describe\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disk\0"
	"distinct\0"
	"distinctrow\0"
	"div\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"duplicate\0"
	"dynamic\0"
	"each\0"
	"else\0"
	"elseif\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"encryption\0"
	"end\0"
	"engine\0"
	"engines\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"exit\0"
	"explain\0"
	"expression\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"fields\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"forward\0"
	"found\0"
	"freeze\0"
	"from\0"
	"full\0"
	"fulltext\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"group_concat\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"high_priority\0"
	"hold\0"
	"hour\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"inplace\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"insert_method\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isolation\0"
	"iterate\0"
	"join\0"
	"key\0"
	"key_block_size\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"leave\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"linear\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"longblob\0"
	"longtext\0"
	"loop\0"
	"low_priority\0"
	"mapping\0"
	"match\0"
	"materialized\0"
	"max_rows\0"
	"maxvalue\0"
	"mediumblob\0"
	"mediumint\0"
	"mediumtext\0"
	"memory\0"
	"merge\0"
	"method\0"
	"mid\0"
	"min_rows\0"
	"minute\0"
	"minvalue\0"
	"mod\0"
	"mode\0"
	"modifies\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"none\0"
	"normalize\0"
	"normalized\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"now\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"nvarchar\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"open\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"pack_keys\0"
	"parallel\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"placing\0"
	"plans\0"
	"plugins\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"processlist\0"
	"program\0"
	"publication\0"
	"quick\0"
	"quote\0"
	"range\0"
	"read\0"
	"reads\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"regexp\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"rlike\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"row_format\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"seletc\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shared\0"
	"show\0"
	"signed\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"spatial\0"
	"sql\0"
	"sql_big_result\0"
	"sql_buffer_result\0"
	"sql_cache\0"
	"sql_calc_found_rows\0"
	"sql_no_cache\0"
	"sql_small_result\0"
	"sqlexception\0"
	"sqlstate\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stats_auto_recalc\0"
	"stats_persistent\0"
	"stats_sample_pages\0"
	"status\0"
	"std\0"
	"stddev\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substr\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"temptable\0"
	"text\0"
	"than\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"timestampadd\0"
	"timestampdiff\0"
	"tinyblob\0"
	"tinyint\0"
	"tinytext\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"triggers\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"undefined\0"
	"unencrypted\0"
	"unicode\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"unsigned\0"
	"until\0"
	"update\0"
	"use\0"
	"user\0"
	"using\0"
	"utc_date\0"
	"utc_time\0"
	"utc_timestamp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varbinary\0"
	"varchar\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"xor\0"
	"year\0"
	"yes\0"
	"zerofill\0"
	"zone";

static const uint16 MysScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	29,
	33,
	39,
	45,
	55,
	65,
	69,
	74,
	80,
	87,
	95,
	103,
	107,
	111,
	121,
	127,
	130,
	134,
	140,
	151,
	161,
	172,
	183,
	186,
	193,
	200,
	210,
	225,
	240,
	249,
	256,
	262,
	270,
	277,
	284,
	288,
	301,
	306,
	311,
	319,
	324,
	332,
	335,
	340,
	346,
	351,
	358,
	366,
	375,
	380,
	385,
	393,
	399,
	406,
	411,
	421,
	437,
	445,
	451,
	462,
	471,
	477,
	483,
	491,
	500,
	508,
	518,
	525,
	539,
	547,
	555,
	564,
	571,
	581,
	593,
	606,
	620,
	629,
	640,
	651,
	663,
	672,
	680,
	689,
	700,
	708,
	713,
	718,
	725,
	731,
	735,
	740,
	748,
	764,
	777,
	790,
	805,
	818,
	836,
	849,
	856,
	862,
	867,
	876,
	886,
	891,
	900,
	904,
	915,
	919,
	927,
	935,
	943,
	952,
	963,
	972,
	980,
	996,
	1004,
	1011,
	1021,
	1032,
	1040,
	1046,
	1051,
	1060,
	1067,
	1081,
	1092,
	1102,
	1110,
	1118,
	1123,
	1132,
	1144,
	1148,
	1151,
	1160,
	1167,
	1174,
	1179,
	1189,
	1197,
	1202,
	1207,
	1214,
	1221,
	1230,
	1240,
	1251,
	1255,
	1262,
	1270,
	1275,
	1282,
	1288,
	1295,
	1303,
	1313,
	1323,
	1331,
	1338,
	1343,
	1351,
	1362,
	1372,
	1381,
	1389,
	1395,
	1402,
	1408,
	1415,
	1422,
	1431,
	1437,
	1443,
	1449,
	1459,
	1463,
	1469,
	1477,
	1485,
	1491,
	1498,
	1503,
	1508,
	1517,
	1526,
	1536,
	1546,
	1550,
	1557,
	1563,
	1571,
	1580,
	1586,
	1599,
	1608,
	1615,
	1623,
	1628,
	1635,
	1642,
	1656,
	1661,
	1666,
	1677,
	1686,
	1689,
	1696,
	1702,
	1712,
	1722,
	1731,
	1738,
	1741,
	1749,
	1759,
	1769,
	1775,
	1783,
	1791,
	1800,
	1810,
	1817,
	1823,
	1829,
	1837,
	1843,
	1855,
	1862,
	1876,
	1884,
	1888,
	1896,
	1906,
	1915,
	1920,
	1930,
	1938,
	1941,
	1951,
	1959,
	1964,
	1968,
	1983,
	1988,
	1994,
	2003,
	2009,
	2014,
	2022,
	2030,
	2040,
	2046,
	2052,
	2057,
	2062,
	2068,
	2073,
	2079,
	2086,
	2091,
	2098,
	2103,
	2109,
	2119,
	2134,
	2143,
	2148,
	2155,
	2162,
	2167,
	2176,
	2185,
	2190,
	2203,
	2211,
	2217,
	2230,
	2239,
	2248,
	2259,
	2269,
	2280,
	2287,
	2293,
	2300,
	2304,
	2313,
	2320,
	2329,
	2333,
	2338,
	2347,
	2354,
	2360,
	2365,
	2370,
	2376,
	2385,
	2393,
	2399,
	2403,
	2408,
	2412,
	2416,
	2421,
	2426,
	2429,
	2434,
	2444,
	2455,
	2459,
	2467,
	2474,
	2482,
	2486,
	2493,
	2498,
	2505,
	2511,
	2519,
	2528,
	2535,
	2538,
	2542,
	2549,
	2554,
	2558,
	2561,
	2566,
	2571,
	2580,
	2587,
	2595,
	2598,
	2604,
	2615,
	2622,
	2626,
	2632,
	2637,
	2646,
	2654,
	2665,
	2671,
	2677,
	2687,
	2696,
	2703,
	2711,
	2721,
	2732,
	2740,
	2749,
	2757,
	2763,
	2771,
	2778,
	2787,
	2797,
	2807,
	2815,
	2824,
	2833,
	2841,
	2847,
	2858,
	2869,
	2879,
	2890,
	2902,
	2910,
	2922,
	2928,
	2934,
	2940,
	2945,
	2951,
	2956,
	2965,
	2973,
	2983,
	2987,
	2998,
	3010,
	3018,
	3025,
	3033,
	3042,
	3050,
	3057,
	3064,
	3075,
	3083,
	3091,
	3097,
	3105,
	3114,
	3121,
	3131,
	3139,
	3146,
	3152,
	3158,
	3163,
	3172,
	3179,
	3187,
	3196,
	3200,
	3211,
	3216,
	3221,
	3231,
	3238,
	3246,
	3253,
	3260,
	3267,
	3276,
	3283,
	3290,
	3300,
	3309,
	3319,
	3332,
	3339,
	3347,
	3360,
	3364,
	3370,
	3375,
	3381,
	3388,
	3393,
	3400,
	3408,
	3415,
	3420,
	3429,
	3438,
	3443,
	3451,
	3455,
	3470,
	3488,
	3498,
	3518,
	3531,
	3548,
	3561,
	3570,
	3577,
	3588,
	3594,
	3604,
	3615,
	3633,
	3650,
	3669,
	3676,
	3680,
	3687,
	3693,
	3700,
	3708,
	3715,
	3722,
	3728,
	3741,
	3755,
	3768,
	3775,
	3785,
	3793,
	3803,
	3809,
	3816,
	3828,
	3834,
	3841,
	3853,
	3864,
	3869,
	3878,
	3888,
	3898,
	3903,
	3908,
	3913,
	3918,
	3923,
	3933,
	3946,
	3960,
	3969,
	3977,
	3986,
	3989,
	3998,
	4010,
	4020,
	4026,
	4034,
	4043,
	4048,
	4053,
	4062,
	4070,
	4075,
	4081,
	4089,
	4099,
	4111,
	4121,
	4133,
	4141,
	4147,
	4154,
	4162,
	4171,
	4178,
	4187,
	4196,
	4202,
	4209,
	4213,
	4218,
	4224,
	4233,
	4242,
	4256,
	4263,
	4269,
	4278,
	4288,
	4294,
	4301,
	4311,
	4319,
	4329,
	4338,
	4346,
	4354,
	4362,
	4367,
	4373,
	4381,
	4389,
	4398,
	4403,
	4409,
	4415,
	4426,
	4433,
	4438,
	4445,
	4453,
	4458,
	4466,
	4472,
	4476,
	4490,
	4500,
	4511,
	4521,
	4531,
	4545,
	4554,
	4560,
	4568,
	4581,
	4590,
	4594,
	4599,
	4603,
	4612,
};

#define MYSSCANKEYWORDS_NUM_KEYWORDS 583

static int
MysScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1167] = {
		0,     -490,  -251,  302,   455,   32767, 32767, -492,
		32767, -58,   32767, 75,    32767, 32767, 32767, 327,
		534,   32767, 52,    32767, 377,   200,   503,   32767,
		32767, 0,     624,   32767, 428,   83,    32767, 350,
		32767, 32767, 32767, 434,   -244,  582,   -865,  32767,
		-27,   32767, 169,   32767, 0,     305,   -293,  32767,
		-732,  4,     223,   32767, 0,     32767, -209,  127,
		32767, 548,   91,    147,   402,   32767, 9,     32767,
		32767, 32767, 32767, 32767, 32767, 32767, 32767, 250,
		32767, 32767, -133,  791,   0,     268,   1072,  32767,
		0,     32767, 170,   409,   32767, 1288,  32767, -335,
		173,   263,   32767, 412,   32767, -217,  32767, -154,
		390,   32767, -11,   1161,  32767, 32767, 32767, -99,
		-236,  137,   32767, 340,   544,   32767, 397,   108,
		111,   213,   -141,  -52,   275,   1322,  32767, 32767,
		32767, 0,     373,   32767, 32767, 32767, 32767, 177,
		-187,  32767, 174,   162,   168,   0,     0,     530,
		32767, 139,   -256,  32767, 32767, 289,   32767, 32767,
		32767, 32767, 305,   32767, -104,  0,     612,   32767,
		32767, 155,   32767, 0,     32767, -454,  32767, 978,
		127,   541,   782,   -482,  172,   32767, 0,     32767,
		32767, 187,   459,   -80,   32767, 32767, 32767, 32767,
		59,    32767, 87,    407,   117,   951,   1364,  496,
		42,    32767, -303,  32767, 343,   32767, 32767, 11,
		355,   332,   224,   103,   32767, 0,     50,    428,
		32767, 32767, -253,  0,     349,   32767, 814,   -136,
		-349,  32767, 32767, 490,   354,   32767, 32767, 32767,
		505,   498,   32767, 0,     32767, 32767, -145,  -313,
		32767, 32767, 810,   276,   0,     32767, 32767, 32767,
		32767, 0,     245,   -201,  -190,  32767, 32767, 32767,
		-539,  -144,  32767, 178,   32767, 32767, -404,  442,
		836,   578,   32767, 32767, 32767, 32767, 335,   32767,
		21,    467,   32767, 744,   318,   -239,  32767, -923,
		0,     0,     39,    32767, 32767, 349,   32767, 450,
		381,   0,     0,     32767, 32767, 322,   260,   32767,
		-171,  32767, 32767, 586,   8,     15,    757,   308,
		428,   0,     32767, 379,   57,    0,     0,     707,
		120,   -79,   241,   -58,   523,   187,   1110,  312,
		-419,  32767, 0,     32767, 32767, 27,    67,    171,
		412,   63,    242,   32767, 32767, 32767, 32767, 32767,
		32767, 188,   0,     0,     32767, 32767, 32767, 549,
		0,     0,     32767, 32767, 32767, 0,     561,   32767,
		-241,  32767, 32767, 32767, 85,    0,     32767, 371,
		-353,  -1,    -405,  -139,  282,   32767, -78,   0,
		32767, 468,   32767, 166,   0,     32767, 0,     196,
		299,   32767, -431,  0,     241,   32767, 299,   530,
		32767, 466,   -589,  0,     192,   44,    32767, 0,
		481,   32767, 340,   32767, -12,   32767, -63,   0,
		32767, 32767, 610,   0,     32767, 32767, 32767, 32767,
		32767, -402,  0,     32767, -276,  32767, 267,   -205,
		32767, 239,   -19,   372,   169,   92,    32767, 0,
		32767, -219,  -3,    0,     290,   32767, 300,   32767,
		32767, 32767, 32767, -245,  32767, 32767, 32767, 458,
		-60,   27,    32767, 63,    393,   32767, 76,    231,
		0,     41,    479,   422,   213,   -736,  0,     58,
		32767, 67,    0,     52,    32767, 32767, 32767, 32767,
		32767, 0,     32767, 283,   360,   265,   118,   32767,
		296,   32767, -266,  83,    199,   -40,   32767, 506,
		32767, 0,     32767, 31,    32767, 352,   32767, 445,
		32767, 32767, 32767, 32767, 858,   0,     112,   32767,
		32767, 88,    0,     32767, 32767, 364,   32767, -61,
		32767, 32767, 587,   64,    256,   32767, -647,  -115,
		232,   -387,  32767, 32767, 0,     32767, 1412,  421,
		1055,  32767, 406,   32767, 465,   -31,   32767, 32767,
		46,    161,   -632,  780,   208,   32767, 513,   0,
		0,     515,   0,     0,     66,    32767, 398,   211,
		853,   0,     72,    32767, 68,    389,   0,     944,
		32767, 19,    323,   32767, -338,  388,   32767, 0,
		-160,  427,   731,   -195,  0,     32767, 32767, 32767,
		514,   -436,  0,     32767, 845,   32767, 561,   -270,
		1071,  32767, -437,  32767, 32767, 32767, 0,     -119,
		0,     32767, 32767, 32767, 32767, 0,     51,    224,
		345,   538,   84,    32767, 32767, 0,     -905,  32767,
		486,   -542,  32767, 440,   487,   0,     32767, -428,
		-336,  142,   -98,   0,     32767, 32767, 32767, 32767,
		615,   -88,   270,   -294,  0,     376,   32767, 0,
		-117,  -128,  319,   -232,  32767, -501,  78,    370,
		0,     32767, 32767, 32767, 160,   225,   32767, 32767,
		834,   32767, 0,     32767, -348,  333,   511,   423,
		437,   475,   32767, -176,  32767, 226,   32767, 32767,
		609,   32767, 648,   163,   -91,   32767, 32767, 32767,
		93,    32767, 32767, 319,   32767, 0,     17,    103,
		489,   876,   32767, 272,   -356,  32767, 32767, 32767,
		32767, 365,   358,   32767, 233,   32767, 0,     102,
		-98,   3,     273,   -177,  67,    -298,  -318,  156,
		32767, 32767, 0,     128,   460,   32767, 32767, 470,
		0,     32767, 32767, 472,   32767, -147,  0,     106,
		0,     32767, -197,  0,     32767, -474,  0,     277,
		32767, 290,   0,     32767, 405,   -242,  32767, -7,
		32767, 31,    32767, 32767, 0,     32767, 0,     32767,
		0,     32767, 0,     439,   -1108, 0,     186,   32767,
		0,     32767, 238,   32767, -327,  0,     0,     32767,
		535,   114,   32767, 153,   -140,  168,   47,    32767,
		1271,  32767, 32767, -1168, 165,   568,   331,   32767,
		181,   32767, 65,    32767, 446,   509,   405,   157,
		24,    318,   509,   396,   0,     -297,  0,     -149,
		135,   32767, 87,    32767, 32767, 448,   32767, 0,
		32767, 729,   32767, 0,     32767, 66,    0,     554,
		-1008, 0,     65,    474,   501,   594,   411,   303,
		213,   32767, 0,     32767, 958,   587,   -165,  0,
		574,   0,     32767, 32767, -172,  201,   32767, 24,
		234,   230,   32767, 32767, -249,  0,     32767, 32767,
		123,   0,     380,   32767, 16,    380,   571,   528,
		32767, -97,   432,   32767, -288,  32767, 32767, 191,
		32767, 25,    32767, 32767, 419,   30,    32767, 338,
		0,     -94,   95,    32,    32767, 723,   -139,  454,
		0,     176,   32767, 1020,  32767, 32767, -313,  -257,
		0,     37,    216,   294,   -69,   479,   32767, 230,
		220,   32767, 32767, 32767, 435,   32767, 32767, 32767,
		-31,   436,   0,     0,     423,   -212,  32767, 462,
		38,    0,     32767, 32767, 649,   0,     0,     32767,
		349,   32767, 32767, 32767, 32767, 554,   32767, 544,
		178,   -529,  -464,  -225,  32767, 229,   350,   32767,
		32767, 0,     534,   -51,   32767, 32767, 0,     107,
		32767, 32767, 622,   56,    491,   32767, 32767, 0,
		32767, -35,   370,   82,    0,     32767, 345,   0,
		32767, -684,  32767, 261,   -495,  212,   1012,  0,
		1377,  0,     79,    97,    157,   -23,   32767, 32767,
		-432,  448,   445,   32767, 32767, 523,   177,   372,
		545,   32767, 145,   32767, 32767, 0,     0,     0,
		0,     565,   32767, -35,   0,     32767, 32767, 32767,
		32767, 113,   259,   32767, 32767, 270,   274,   453,
		-187,  567,   0,     0,     32767, 0,     32767, 0,
		-193,  10,    32767, 30,    -318,  259,   472,   146,
		253,   32767, 32767, -947,  262,   32767, 576,   32767,
		32767, 349,   238,   12,    32767, -784,  545,   32767,
		544,   32767, 32767, 32767, 32767, 0,     32767, 527,
		-235,  20,    281,   572,   0,     341,   0,     488,
		32767, 32767, 484,   32767, 390,   32767, 0,     32767,
		32767, 113,   0,     114,   32767, 201,   32767, 54,
		32767, 562,   32767, 32767, 32767, 23,    32767, 32767,
		-391,  -1030, 0,     32767, 32767, 254,   0,     391,
		648,   81,    923,   32767, 899,   32767, 519,   32767,
		32767, 32767, -264,  32767, 798,   449,   0,     165,
		266,   32767, 32767, 0,     0,     32767, 0,     447,
		436,   32767, 805,   0,     487,   32767, 0,     89,
		-460,  32767, 0,     -410,  537,   -17,   0,     0,
		-737,  0,     32767, 32767, -381,  0,     523,   32767,
		0,     32767, 0,     32767, 0,     138,   77,    0,
		0,     32767, 109,   0,     34,    32767, 0,     -273,
		0,     457,   -21,   508,   0,     475,   32767, 0,
		0,     10,    0,     32767, 550,   32767, 0,     32767,
		532,   3,     0,     32767, 384,   0,     32767, 920,
		479,   0,     32767, 213,   30,    0,     32767, 32767,
		32767, 149,   130,   1008,  423,   722,   32767, -221,
		32767, 0,     32767, -419,  32767, 32767, 32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 0;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1167] + h[b % 1167];
}

const ScanKeywordList MysScanKeywords = {
	MysScanKeywords_kw_string,
	MysScanKeywords_kw_offsets,
	MysScanKeywords_hash_func,
	MYSSCANKEYWORDS_NUM_KEYWORDS,
	19
};

#endif							/* MYS_KWLIST_D_H */
