/*-------------------------------------------------------------------------
 *
 * mys_kwlist_d.h
 *    List of keywords represented as a ScanKeywordList.
 *
 * Portions Copyright (c) 1996-2025, PostgreSQL Global Development Group
 * Portions Copyright (c) 1994, Regents of the University of California
 *
 * NOTES
 *  ******************************
 *  *** DO NOT EDIT THIS FILE! ***
 *  ******************************
 *
 *  It has been GENERATED by src/tools/gen_keywordlist.pl
 *
 *-------------------------------------------------------------------------
 */

#ifndef MYS_KWLIST_D_H
#define MYS_KWLIST_D_H

#include "common/kwlookup.h"

static const char MysScanKeywords_kw_string[] =
	"abort\0"
	"absolute\0"
	"access\0"
	"action\0"
	"add\0"
	"admin\0"
	"after\0"
	"aggregate\0"
	"algorithm\0"
	"all\0"
	"also\0"
	"alter\0"
	"always\0"
	"analyse\0"
	"analyze\0"
	"and\0"
	"any\0"
	"any_value\0"
	"array\0"
	"as\0"
	"asc\0"
	"ascii\0"
	"asensitive\0"
	"assertion\0"
	"assignment\0"
	"asymmetric\0"
	"at\0"
	"atomic\0"
	"attach\0"
	"attribute\0"
	"auto_increment\0"
	"avg_row_length\0"
	"backward\0"
	"before\0"
	"begin\0"
	"between\0"
	"bigint\0"
	"binary\0"
	"bit\0"
	"bit_as_bytea\0"
	"blob\0"
	"bool\0"
	"boolean\0"
	"both\0"
	"breadth\0"
	"by\0"
	"byte\0"
	"cache\0"
	"call\0"
	"called\0"
	"cascade\0"
	"cascaded\0"
	"case\0"
	"cast\0"
	"catalog\0"
	"chain\0"
	"change\0"
	"char\0"
	"character\0"
	"characteristics\0"
	"charset\0"
	"check\0"
	"checkpoint\0"
	"checksum\0"
	"class\0"
	"close\0"
	"cluster\0"
	"coalesce\0"
	"collate\0"
	"collation\0"
	"column\0"
	"column_format\0"
	"columns\0"
	"comment\0"
	"comments\0"
	"commit\0"
	"committed\0"
	"compression\0"
	"concurrently\0"
	"configuration\0"
	"conflict\0"
	"connection\0"
	"constraint\0"
	"constraints\0"
	"contains\0"
	"content\0"
	"continue\0"
	"conversion\0"
	"convert\0"
	"copy\0"
	"cost\0"
	"create\0"
	"cross\0"
	"csv\0"
	"cube\0"
	"current\0"
	"current_catalog\0"
	"current_date\0"
	"current_role\0"
	"current_schema\0"
	"current_time\0"
	"current_timestamp\0"
	"current_user\0"
	"cursor\0"
	"cycle\0"
	"data\0"
	"database\0"
	"databases\0"
	"date\0"
	"datetime\0"
	"day\0"
	"deallocate\0"
	"dec\0"
	"decimal\0"
	"declare\0"
	"default\0"
	"defaults\0"
	"deferrable\0"
	"deferred\0"
	"definer\0"
	"delay_key_write\0"
	"delayed\0"
	"delete\0"
	"delimiter\0"
	"delimiters\0"
	"depends\0"
	"depth\0"
	"desc\0"
	"describe\0"
	"detach\0"
	"deterministic\0"
	"dictionary\0"
	"directory\0"
	"disable\0"
	"discard\0"
	"disk\0"
	"distinct\0"
	"distinctrow\0"
	"div\0"
	"do\0"
	"document\0"
	"domain\0"
	"double\0"
	"drop\0"
	"duplicate\0"
	"dynamic\0"
	"each\0"
	"else\0"
	"elseif\0"
	"enable\0"
	"encoding\0"
	"encrypted\0"
	"encryption\0"
	"end\0"
	"engine\0"
	"engines\0"
	"enum\0"
	"escape\0"
	"event\0"
	"except\0"
	"exclude\0"
	"excluding\0"
	"exclusive\0"
	"execute\0"
	"exists\0"
	"exit\0"
	"explain\0"
	"expression\0"
	"extension\0"
	"external\0"
	"extract\0"
	"false\0"
	"family\0"
	"fetch\0"
	"fields\0"
	"filter\0"
	"finalize\0"
	"first\0"
	"fixed\0"
	"float\0"
	"following\0"
	"for\0"
	"force\0"
	"foreign\0"
	"forward\0"
	"found\0"
	"freeze\0"
	"from\0"
	"full\0"
	"fulltext\0"
	"function\0"
	"functions\0"
	"generated\0"
	"get\0"
	"global\0"
	"grant\0"
	"granted\0"
	"greatest\0"
	"group\0"
	"group_concat\0"
	"grouping\0"
	"groups\0"
	"handler\0"
	"hash\0"
	"having\0"
	"header\0"
	"high_priority\0"
	"hold\0"
	"hour\0"
	"identified\0"
	"identity\0"
	"if\0"
	"ignore\0"
	"ilike\0"
	"immediate\0"
	"immutable\0"
	"implicit\0"
	"import\0"
	"in\0"
	"include\0"
	"including\0"
	"increment\0"
	"index\0"
	"indexes\0"
	"inherit\0"
	"inherits\0"
	"initially\0"
	"inline\0"
	"inner\0"
	"inout\0"
	"inplace\0"
	"input\0"
	"insensitive\0"
	"insert\0"
	"insert_method\0"
	"instead\0"
	"int\0"
	"integer\0"
	"intersect\0"
	"interval\0"
	"into\0"
	"invisible\0"
	"invoker\0"
	"is\0"
	"isolation\0"
	"iterate\0"
	"join\0"
	"key\0"
	"key_block_size\0"
	"keys\0"
	"label\0"
	"language\0"
	"large\0"
	"last\0"
	"lateral\0"
	"leading\0"
	"leakproof\0"
	"least\0"
	"leave\0"
	"left\0"
	"less\0"
	"level\0"
	"like\0"
	"limit\0"
	"linear\0"
	"list\0"
	"listen\0"
	"load\0"
	"local\0"
	"localtime\0"
	"localtimestamp\0"
	"location\0"
	"lock\0"
	"locked\0"
	"logged\0"
	"long\0"
	"longblob\0"
	"longtext\0"
	"loop\0"
	"low_priority\0"
	"mapping\0"
	"match\0"
	"materialized\0"
	"max_rows\0"
	"maxvalue\0"
	"mediumblob\0"
	"mediumint\0"
	"mediumtext\0"
	"memory\0"
	"merge\0"
	"method\0"
	"mid\0"
	"min_rows\0"
	"minute\0"
	"minvalue\0"
	"mod\0"
	"mode\0"
	"modifies\0"
	"modify\0"
	"month\0"
	"move\0"
	"name\0"
	"names\0"
	"national\0"
	"natural\0"
	"nchar\0"
	"new\0"
	"next\0"
	"nfc\0"
	"nfd\0"
	"nfkc\0"
	"nfkd\0"
	"no\0"
	"none\0"
	"normalize\0"
	"normalized\0"
	"not\0"
	"nothing\0"
	"notify\0"
	"notnull\0"
	"now\0"
	"nowait\0"
	"null\0"
	"nullif\0"
	"nulls\0"
	"numeric\0"
	"nvarchar\0"
	"object\0"
	"of\0"
	"off\0"
	"offset\0"
	"oids\0"
	"old\0"
	"on\0"
	"only\0"
	"open\0"
	"operator\0"
	"option\0"
	"options\0"
	"or\0"
	"order\0"
	"ordinality\0"
	"others\0"
	"out\0"
	"outer\0"
	"over\0"
	"overlaps\0"
	"overlay\0"
	"overriding\0"
	"owned\0"
	"owner\0"
	"pack_keys\0"
	"parallel\0"
	"parser\0"
	"partial\0"
	"partition\0"
	"partitions\0"
	"passing\0"
	"password\0"
	"placing\0"
	"plans\0"
	"plugins\0"
	"policy\0"
	"position\0"
	"preceding\0"
	"precision\0"
	"prepare\0"
	"prepared\0"
	"preserve\0"
	"primary\0"
	"prior\0"
	"privileges\0"
	"procedural\0"
	"procedure\0"
	"procedures\0"
	"processlist\0"
	"program\0"
	"publication\0"
	"quick\0"
	"quote\0"
	"range\0"
	"read\0"
	"reads\0"
	"real\0"
	"reassign\0"
	"recheck\0"
	"recursive\0"
	"ref\0"
	"references\0"
	"referencing\0"
	"refresh\0"
	"regexp\0"
	"reindex\0"
	"relative\0"
	"release\0"
	"rename\0"
	"repeat\0"
	"repeatable\0"
	"replace\0"
	"replica\0"
	"reset\0"
	"restart\0"
	"restrict\0"
	"return\0"
	"returning\0"
	"returns\0"
	"revoke\0"
	"right\0"
	"rlike\0"
	"role\0"
	"rollback\0"
	"rollup\0"
	"routine\0"
	"routines\0"
	"row\0"
	"row_format\0"
	"rows\0"
	"rule\0"
	"savepoint\0"
	"schema\0"
	"schemas\0"
	"scroll\0"
	"search\0"
	"second\0"
	"security\0"
	"select\0"
	"seletc\0"
	"separator\0"
	"sequence\0"
	"sequences\0"
	"serializable\0"
	"server\0"
	"session\0"
	"session_user\0"
	"set\0"
	"setof\0"
	"sets\0"
	"share\0"
	"shared\0"
	"show\0"
	"signed\0"
	"similar\0"
	"simple\0"
	"skip\0"
	"smallint\0"
	"snapshot\0"
	"some\0"
	"spatial\0"
	"sql\0"
	"sql_big_result\0"
	"sql_buffer_result\0"
	"sql_cache\0"
	"sql_no_cache\0"
	"sql_small_result\0"
	"sqlexception\0"
	"sqlstate\0"
	"stable\0"
	"standalone\0"
	"start\0"
	"statement\0"
	"statistics\0"
	"stats_auto_recalc\0"
	"stats_persistent\0"
	"stats_sample_pages\0"
	"status\0"
	"std\0"
	"stddev\0"
	"stdin\0"
	"stdout\0"
	"storage\0"
	"stored\0"
	"strict\0"
	"strip\0"
	"subpartition\0"
	"subpartitions\0"
	"subscription\0"
	"substr\0"
	"substring\0"
	"support\0"
	"symmetric\0"
	"sysid\0"
	"system\0"
	"system_user\0"
	"table\0"
	"tables\0"
	"tablesample\0"
	"tablespace\0"
	"temp\0"
	"template\0"
	"temporary\0"
	"temptable\0"
	"text\0"
	"than\0"
	"then\0"
	"ties\0"
	"time\0"
	"timestamp\0"
	"timestampadd\0"
	"timestampdiff\0"
	"tinyblob\0"
	"tinyint\0"
	"tinytext\0"
	"to\0"
	"trailing\0"
	"transaction\0"
	"transform\0"
	"treat\0"
	"trigger\0"
	"triggers\0"
	"trim\0"
	"true\0"
	"truncate\0"
	"trusted\0"
	"type\0"
	"types\0"
	"uescape\0"
	"unbounded\0"
	"uncommitted\0"
	"undefined\0"
	"unencrypted\0"
	"unicode\0"
	"union\0"
	"unique\0"
	"unknown\0"
	"unlisten\0"
	"unlock\0"
	"unlogged\0"
	"unsigned\0"
	"until\0"
	"update\0"
	"use\0"
	"user\0"
	"using\0"
	"utc_date\0"
	"utc_time\0"
	"utc_timestamp\0"
	"vacuum\0"
	"valid\0"
	"validate\0"
	"validator\0"
	"value\0"
	"values\0"
	"varbinary\0"
	"varchar\0"
	"variables\0"
	"variadic\0"
	"varying\0"
	"verbose\0"
	"version\0"
	"view\0"
	"views\0"
	"virtual\0"
	"visible\0"
	"volatile\0"
	"when\0"
	"where\0"
	"while\0"
	"whitespace\0"
	"window\0"
	"with\0"
	"within\0"
	"without\0"
	"work\0"
	"wrapper\0"
	"write\0"
	"xml\0"
	"xmlattributes\0"
	"xmlconcat\0"
	"xmlelement\0"
	"xmlexists\0"
	"xmlforest\0"
	"xmlnamespaces\0"
	"xmlparse\0"
	"xmlpi\0"
	"xmlroot\0"
	"xmlserialize\0"
	"xmltable\0"
	"xor\0"
	"year\0"
	"yes\0"
	"zerofill\0"
	"zone";

static const uint16 MysScanKeywords_kw_offsets[] = {
	0,
	6,
	15,
	22,
	29,
	33,
	39,
	45,
	55,
	65,
	69,
	74,
	80,
	87,
	95,
	103,
	107,
	111,
	121,
	127,
	130,
	134,
	140,
	151,
	161,
	172,
	183,
	186,
	193,
	200,
	210,
	225,
	240,
	249,
	256,
	262,
	270,
	277,
	284,
	288,
	301,
	306,
	311,
	319,
	324,
	332,
	335,
	340,
	346,
	351,
	358,
	366,
	375,
	380,
	385,
	393,
	399,
	406,
	411,
	421,
	437,
	445,
	451,
	462,
	471,
	477,
	483,
	491,
	500,
	508,
	518,
	525,
	539,
	547,
	555,
	564,
	571,
	581,
	593,
	606,
	620,
	629,
	640,
	651,
	663,
	672,
	680,
	689,
	700,
	708,
	713,
	718,
	725,
	731,
	735,
	740,
	748,
	764,
	777,
	790,
	805,
	818,
	836,
	849,
	856,
	862,
	867,
	876,
	886,
	891,
	900,
	904,
	915,
	919,
	927,
	935,
	943,
	952,
	963,
	972,
	980,
	996,
	1004,
	1011,
	1021,
	1032,
	1040,
	1046,
	1051,
	1060,
	1067,
	1081,
	1092,
	1102,
	1110,
	1118,
	1123,
	1132,
	1144,
	1148,
	1151,
	1160,
	1167,
	1174,
	1179,
	1189,
	1197,
	1202,
	1207,
	1214,
	1221,
	1230,
	1240,
	1251,
	1255,
	1262,
	1270,
	1275,
	1282,
	1288,
	1295,
	1303,
	1313,
	1323,
	1331,
	1338,
	1343,
	1351,
	1362,
	1372,
	1381,
	1389,
	1395,
	1402,
	1408,
	1415,
	1422,
	1431,
	1437,
	1443,
	1449,
	1459,
	1463,
	1469,
	1477,
	1485,
	1491,
	1498,
	1503,
	1508,
	1517,
	1526,
	1536,
	1546,
	1550,
	1557,
	1563,
	1571,
	1580,
	1586,
	1599,
	1608,
	1615,
	1623,
	1628,
	1635,
	1642,
	1656,
	1661,
	1666,
	1677,
	1686,
	1689,
	1696,
	1702,
	1712,
	1722,
	1731,
	1738,
	1741,
	1749,
	1759,
	1769,
	1775,
	1783,
	1791,
	1800,
	1810,
	1817,
	1823,
	1829,
	1837,
	1843,
	1855,
	1862,
	1876,
	1884,
	1888,
	1896,
	1906,
	1915,
	1920,
	1930,
	1938,
	1941,
	1951,
	1959,
	1964,
	1968,
	1983,
	1988,
	1994,
	2003,
	2009,
	2014,
	2022,
	2030,
	2040,
	2046,
	2052,
	2057,
	2062,
	2068,
	2073,
	2079,
	2086,
	2091,
	2098,
	2103,
	2109,
	2119,
	2134,
	2143,
	2148,
	2155,
	2162,
	2167,
	2176,
	2185,
	2190,
	2203,
	2211,
	2217,
	2230,
	2239,
	2248,
	2259,
	2269,
	2280,
	2287,
	2293,
	2300,
	2304,
	2313,
	2320,
	2329,
	2333,
	2338,
	2347,
	2354,
	2360,
	2365,
	2370,
	2376,
	2385,
	2393,
	2399,
	2403,
	2408,
	2412,
	2416,
	2421,
	2426,
	2429,
	2434,
	2444,
	2455,
	2459,
	2467,
	2474,
	2482,
	2486,
	2493,
	2498,
	2505,
	2511,
	2519,
	2528,
	2535,
	2538,
	2542,
	2549,
	2554,
	2558,
	2561,
	2566,
	2571,
	2580,
	2587,
	2595,
	2598,
	2604,
	2615,
	2622,
	2626,
	2632,
	2637,
	2646,
	2654,
	2665,
	2671,
	2677,
	2687,
	2696,
	2703,
	2711,
	2721,
	2732,
	2740,
	2749,
	2757,
	2763,
	2771,
	2778,
	2787,
	2797,
	2807,
	2815,
	2824,
	2833,
	2841,
	2847,
	2858,
	2869,
	2879,
	2890,
	2902,
	2910,
	2922,
	2928,
	2934,
	2940,
	2945,
	2951,
	2956,
	2965,
	2973,
	2983,
	2987,
	2998,
	3010,
	3018,
	3025,
	3033,
	3042,
	3050,
	3057,
	3064,
	3075,
	3083,
	3091,
	3097,
	3105,
	3114,
	3121,
	3131,
	3139,
	3146,
	3152,
	3158,
	3163,
	3172,
	3179,
	3187,
	3196,
	3200,
	3211,
	3216,
	3221,
	3231,
	3238,
	3246,
	3253,
	3260,
	3267,
	3276,
	3283,
	3290,
	3300,
	3309,
	3319,
	3332,
	3339,
	3347,
	3360,
	3364,
	3370,
	3375,
	3381,
	3388,
	3393,
	3400,
	3408,
	3415,
	3420,
	3429,
	3438,
	3443,
	3451,
	3455,
	3470,
	3488,
	3498,
	3511,
	3528,
	3541,
	3550,
	3557,
	3568,
	3574,
	3584,
	3595,
	3613,
	3630,
	3649,
	3656,
	3660,
	3667,
	3673,
	3680,
	3688,
	3695,
	3702,
	3708,
	3721,
	3735,
	3748,
	3755,
	3765,
	3773,
	3783,
	3789,
	3796,
	3808,
	3814,
	3821,
	3833,
	3844,
	3849,
	3858,
	3868,
	3878,
	3883,
	3888,
	3893,
	3898,
	3903,
	3913,
	3926,
	3940,
	3949,
	3957,
	3966,
	3969,
	3978,
	3990,
	4000,
	4006,
	4014,
	4023,
	4028,
	4033,
	4042,
	4050,
	4055,
	4061,
	4069,
	4079,
	4091,
	4101,
	4113,
	4121,
	4127,
	4134,
	4142,
	4151,
	4158,
	4167,
	4176,
	4182,
	4189,
	4193,
	4198,
	4204,
	4213,
	4222,
	4236,
	4243,
	4249,
	4258,
	4268,
	4274,
	4281,
	4291,
	4299,
	4309,
	4318,
	4326,
	4334,
	4342,
	4347,
	4353,
	4361,
	4369,
	4378,
	4383,
	4389,
	4395,
	4406,
	4413,
	4418,
	4425,
	4433,
	4438,
	4446,
	4452,
	4456,
	4470,
	4480,
	4491,
	4501,
	4511,
	4525,
	4534,
	4540,
	4548,
	4561,
	4570,
	4574,
	4579,
	4583,
	4592,
};

#define MYSSCANKEYWORDS_NUM_KEYWORDS 582

static int
MysScanKeywords_hash_func(const void *key, size_t keylen)
{
	static const int16 h[1165] = {
		32767, -294,  278,   300,   70,    32767, 32767, 32767,
		32767, 63,    172,   32767, 447,   -285,  32767, 32767,
		32767, 156,   458,   362,   32767, 32767, -192,  396,
		185,   47,    32767, 302,   223,   -115,  -265,  0,
		187,   0,     32767, 471,   -57,   575,   294,   -60,
		0,     89,    57,    -165,  32767, -701,  1,     0,
		-217,  32767, 0,     0,     -116,  -61,   429,   371,
		32767, -103,  212,   -980,  334,   775,   32767, 32767,
		772,   263,   345,   65,    59,    0,     553,   807,
		32767, 439,   58,    115,   365,   0,     32767, 59,
		32767, 259,   -234,  -169,  379,   24,    0,     797,
		-613,  32767, 32767, 32767, 32767, 32767, 353,   -257,
		-182,  32767, 32767, 32767, 1093,  224,   680,   0,
		32767, 0,     32767, 32767, 77,    114,   32767, 139,
		96,    99,    -186,  32767, 32767, 147,   49,    -276,
		0,     327,   32767, 32767, 271,   32767, 32767, -648,
		0,     0,     -181,  370,   588,   112,   0,     24,
		32767, 670,   32767, 218,   32767, 151,   32767, 32767,
		195,   90,    276,   32767, 479,   572,   32767, 350,
		32767, 32767, 32767, 254,   -616,  32767, 952,   115,
		32767, 32,    412,   32767, 0,     755,   541,   394,
		0,     407,   32767, 32767, 78,    -279,  32767, 0,
		478,   0,     32767, 32767, 32767, -390,  723,   32767,
		32767, 82,    32767, 32767, 1078,  32767, 764,   1426,
		32767, -387,  67,    32767, 32767, 32767, 0,     0,
		32767, 32767, 32767, -526,  -552,  32767, 9,     574,
		797,   -241,  -74,   317,   -122,  321,   32767, 32767,
		0,     32767, 32767, 117,   385,   398,   32767, 32767,
		922,   0,     32767, 428,   388,   32767, 32767, 32767,
		-518,  -383,  32767, 449,   157,   63,    432,   32767,
		0,     500,   32767, 256,   0,     799,   -907,  32767,
		32767, -143,  -801,  32767, 0,     32767, 93,    387,
		32767, 32767, 32767, 0,     32767, 32767, 477,   256,
		32767, 32767, 0,     658,   329,   341,   156,   32767,
		0,     32767, 421,   32767, 32767, 32767, 614,   100,
		32767, 464,   126,   206,   668,   0,     40,    234,
		142,   189,   32767, 32767, 378,   32767, 32767, 32767,
		-33,   32767, 32767, 102,   -901,  32767, 32767, 564,
		32767, 1011,  159,   32767, 448,   32767, 32767, -448,
		32767, 460,   32767, 1055,  32767, 0,     32767, -40,
		32767, 0,     -106,  32767, 32767, 32767, -193,  32767,
		316,   208,   32767, 113,   437,   124,   32767, 32767,
		0,     32767, 32767, 0,     32767, 32767, 451,   32767,
		32767, 549,   67,    32767, 492,   227,   32767, 32767,
		32767, -543,  141,   538,   130,   410,   -389,  174,
		32767, 32767, 32767, -2,    32767, 505,   392,   0,
		38,    34,    -321,  64,    32767, 32767, 1041,  178,
		131,   32767, 32767, 32767, 32767, 32767, 99,    32767,
		-425,  32767, 32767, 32767, 21,    32767, 543,   314,
		32767, 41,    531,   -22,   32767, -22,   32767, -77,
		552,   304,   -547,  0,     32767, 32767, 0,     32767,
		-85,   813,   -137,  374,   0,     32767, 32767, -175,
		25,    32767, 32767, 32767, 676,   224,   -230,  87,
		-70,   0,     0,     0,     0,     32767, 32767, 32767,
		32767, 32767, 0,     32767, 32767, 32767, 0,     481,
		441,   -167,  -504,  528,   0,     550,   -175,  213,
		32767, 1119,  198,   32767, 32767, 32767, -768,  140,
		157,   -813,  32767, 32767, -452,  474,   32767, 172,
		0,     569,   520,   32767, 32767, 0,     32767, 579,
		0,     74,    32767, -819,  32767, 0,     770,   32767,
		383,   537,   32767, 32767, 181,   -62,   32767, 32767,
		272,   412,   32767, 0,     32767, 580,   32767, 32767,
		670,   -109,  32767, 32767, 414,   475,   0,     -34,
		34,    205,   32767, 235,   32767, -345,  232,   106,
		32767, 32767, 32767, 32767, 32767, 32767, 0,     32767,
		32767, 237,   32767, -210,  83,    86,    806,   -4,
		32767, 568,   -312,  32767, 66,    32767, 228,   595,
		461,   32767, 32767, 208,   32767, 32767, -269,  0,
		32767, 6,     -231,  977,   -943,  -280,  536,   318,
		-419,  32767, 32767, 76,    562,   32767, 32767, 350,
		32767, 32767, 0,     507,   0,     222,   32767, 88,
		509,   0,     32767, 32767, 32767, 32767, 32767, 0,
		32767, 32767, 14,    -430,  26,    32767, -20,   586,
		32767, 32767, 0,     32767, 4,     32767, 565,   0,
		664,   0,     32767, 32767, -180,  0,     -332,  500,
		-364,  -118,  237,   449,   0,     -283,  -153,  32767,
		32767, 82,    -437,  -752,  0,     0,     32767, 32767,
		0,     -90,   239,   32767, 70,    32767, 211,   32767,
		32767, 65,    32767, 32767, 399,   32767, 360,   0,
		915,   0,     32767, 0,     200,   358,   32767, 32767,
		0,     0,     32767, -545,  32767, 5,     32767, 32767,
		83,    32767, 380,   0,     32767, 266,   125,   0,
		649,   75,    422,   416,   499,   271,   32767, 32767,
		0,     32767, 54,    0,     1034,  34,    0,     220,
		513,   964,   0,     32767, -940,  332,   32767, 616,
		32767, 339,   419,   -93,   76,    32767, 0,     32767,
		32767, 1325,  32767, 32767, 32767, 36,    32767, 440,
		32767, 32767, 600,   796,   32767, 459,   0,     0,
		60,    0,     32767, 95,    209,   32767, 32767, 107,
		0,     32767, 32767, 32767, 32767, 0,     32767, 32767,
		203,   32767, 0,     32767, 32767, 206,   0,     152,
		0,     32767, 32767, 32767, 0,     -186,  287,   32767,
		1097,  -151,  215,   32767, 32767, 624,   213,   452,
		32767, 32767, -138,  27,    0,     297,   160,   0,
		201,   78,    656,   32767, 468,   108,   129,   34,
		32767, 473,   153,   317,   32767, 1061,  -174,  -655,
		32767, -11,   32767, 493,   -55,   32767, 872,   32767,
		-139,  32767, 32767, 83,    0,     163,   0,     85,
		10,    32767, 425,   32767, 476,   32767, 818,   32767,
		13,    272,   -195,  32767, 32767, 776,   83,    32767,
		155,   247,   0,     0,     32767, 32767, 327,   90,
		32767, 23,    20,    503,   0,     32767, 32767, 280,
		32767, 32767, 32767, 640,   313,   151,   840,   331,
		1240,  32767, 32767, 32767, 15,    0,     0,     133,
		-110,  298,   431,   32767, 1145,  0,     -137,  32767,
		-196,  209,   -1052, 32767, 159,   32767, 76,    134,
		0,     -435,  32767, 0,     514,   32767, -22,   -139,
		32767, 32767, 32767, -175,  32767, 32767, 304,   438,
		405,   32767, 254,   -145,  -412,  326,   32767, 0,
		0,     32767, 0,     321,   32767, 414,   32767, 0,
		-764,  684,   -472,  32767, 0,     0,     547,   -733,
		224,   225,   32767, 32767, 220,   32767, -708,  32767,
		306,   531,   32767, 0,     32767, 275,   324,   134,
		357,   0,     0,     0,     451,   985,   32767, 172,
		251,   139,   32767, 32767, 562,   0,     32767, 215,
		245,   -203,  -653,  0,     -272,  32767, -63,   -344,
		0,     41,    32767, 250,   249,   32767, 32767, 32767,
		0,     0,     32767, 32767, 0,     362,   512,   44,
		32767, -26,   0,     715,   41,    32767, 259,   32767,
		32767, 453,   32767, -695,  32767, 0,     389,   0,
		32767, 1013,  0,     302,   -250,  59,    32767, 73,
		32767, 56,    175,   937,   556,   32767, 32767, 423,
		32767, 32767, 32767, 32767, 529,   0,     230,   325,
		32767, 32767, 32767, -242,  32767, 313,   32767, 303,
		561,   130,   351,   383,   988,   0,     32767, 0,
		32767, 57,    390,   32767, 0,     32767, 0,     219,
		32767, 283,   -160,  32767, 855,   32767, 32767, 248,
		99,    32767, 162,   32767, 32767, 32767, 154,   -22,
		-267,  0,     32767, 32767, 0,     32767, 337,   523,
		374,   -321,  235,   576,   32767, 0,     0,     0,
		32767, 39,    0,     391,   1222,  32767, 32767, 0,
		32767, 546,   286,   32767, 812,   462,   320,   193,
		432,   0,     18,    -22,   32767, 32767, 0,     32767,
		-127,  32767, 577,   32767, 0,     510,   336,   32767,
		32767, 606,   374,   32767, 32767, 0,     368,   32767,
		0,     539,   32767, 288,   -104,  88,    32767, 0,
		0,     -215,  32767, -321,  0,     994,   32767, 388,
		8,     46,    -93,   262,   -660,  0,     348,   508,
		32767, 32767, 0,     0,     0,     271,   32767, 406,
		32767, 32767, 32767, 0,     52,    32767, 32767, 32767,
		32767, 0,     32767, 32767, 577,   32767, 347,   32767,
		-318,  183,   32767, -384,  0,     483,   96,    87,
		320,   57,    0,     32767, -1119, 32767, 32767, 32767,
		525,   32767, -182,  678,   0,     0,     -70,   504,
		0,     186,   189,   332,   0,     32767, 32767, 32767,
		32767, 32767, 33,    32767, 32767
	};

	const unsigned char *k = (const unsigned char *) key;
	uint32		a = 0;
	uint32		b = 1;

	while (keylen--)
	{
		unsigned char c = *k++ | 0x20;

		a = a * 257 + c;
		b = b * 127 + c;
	}
	return h[a % 1165] + h[b % 1165];
}

const ScanKeywordList MysScanKeywords = {
	MysScanKeywords_kw_string,
	MysScanKeywords_kw_offsets,
	MysScanKeywords_hash_func,
	MYSSCANKEYWORDS_NUM_KEYWORDS,
	18
};

#endif							/* MYS_KWLIST_D_H */
