#-------------------------------------------------------------------------
#
# Makefile for src/pl/plmysql (openHalo MySQL procedural language)
#
# src/pl/plmysql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/pl/plmysql
top_builddir = ../../..
include $(top_builddir)/src/Makefile.global

SUBDIRS = src

$(recurse)
