#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/adapter/mysql
#
# IDENTIFICATION
#    src/backend/adapter/mysql/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/adapter/mysql
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	mysql_packet.o \
	mysql_auth.o \
	mysql_command.o \
	mysql_protocol.o

include $(top_srcdir)/src/backend/common.mk
